# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Reference Implementation Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Reference Implementation Swift
  #pod 'TallyGoKit-Xcode9.2'
  pod 'TallyGoKit-Xcode9.2', path: '../'

end
